
[[keymaps]]
command="None"
key_sequence="l"

[[keymaps]]
command = "LikedTrackPage"
key_sequence = "C-l"

[[keymaps]]
command = "SearchPage"
key_sequence = "C-s"

[[actions]]
action="AddToLiked"
key_sequence="l"

[[actions]]
action="DeleteFromLiked"
key_sequence="L"

[[actions]]
action="GoToArtist"
key_sequence="C-a"

